export const jiraTasks = [
  {
    id: "FRONT-551",
    title: "Add lazy-loading for image gallery",
    type: "Story",
    status: "IN_PROGRESS",
    priority: "HIGH",
    reporter: "Anup",
    assignee: "Sagar",
    sprint: "Sprint 14",
    epic: "Performance Optimizations",
    tags: ["react", "performance", "ui"],
    updated: "2025-11-29T10:22:00Z",
    created: "2025-11-20T09:10:00Z"
  },
  {
    id: "AUTH-139",
    title: "Fix refresh token rotation issue",
    type: "Bug",
    status: "TODO",
    priority: "CRITICAL",
    reporter: "Anup",
    assignee: "Amit",
    sprint: "Sprint 15",
    epic: "Security Enhancements",
    tags: ["auth", "backend", "security"],
    updated: "2025-11-30T07:14:00Z",
    created: "2025-11-28T11:02:00Z"
  },
  {
    id: "DASH-92",
    title: "Implement analytics line chart",
    type: "Task",
    status: "REVIEW",
    priority: "MEDIUM",
    reporter: "Riya",
    assignee: "Riya",
    sprint: "Sprint 14",
    epic: "Analytics Dashboard",
    tags: ["charts", "frontend", "d3"],
    updated: "2025-11-30T03:05:00Z",
    created: "2025-11-21T13:44:00Z"
  },
  {
    id: "AUTH-140",
    title: "Add multi-factor authentication (MFA)",
    type: "Story",
    status: "IN_PROGRESS",
    priority: "CRITICAL",
    reporter: "John",
    assignee: "Anup",
    sprint: "Sprint 15",
    epic: "Security Enhancements",
    tags: ["auth", "backend", "otp"],
    updated: "2025-11-29T18:47:00Z",
    created: "2025-11-18T07:58:00Z"
  },
  {
    id: "FRONT-552",
    title: "Create reusable Tooltip component",
    type: "Task",
    status: "TODO",
    priority: "LOW",
    reporter: "Sara",
    assignee: "Aakash",
    sprint: "Backlog",
    epic: "UI Library",
    tags: ["design-system", "react"],
    updated: "2025-11-30T10:54:00Z",
    created: "2025-11-26T15:12:00Z"
  },
  {
    id: "FRONT-553",
    title: "Responsive navbar improvements",
    type: "Story",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    reporter: "Amit",
    assignee: "Sara",
    sprint: "Sprint 14",
    epic: "UI Enhancements",
    tags: ["responsive", "css"],
    updated: "2025-11-30T10:11:00Z",
    created: "2025-11-17T12:10:00Z"
  },
  {
    id: "DASH-93",
    title: "Add loading skeletons for dashboard widgets",
    type: "Task",
    status: "TODO",
    priority: "MEDIUM",
    reporter: "Sachin",
    assignee: "Meena",
    sprint: "Sprint 15",
    epic: "Analytics Dashboard",
    tags: ["react", "ui", "skeleton"],
    updated: "2025-11-29T06:18:00Z",
    created: "2025-11-22T16:37:00Z"
  },
  {
    id: "AUTH-141",
    title: "Fix race condition in OTP resend flow",
    type: "Bug",
    status: "REVIEW",
    priority: "HIGH",
    reporter: "Anup",
    assignee: "Anup",
    sprint: "Sprint 14",
    epic: "Security Enhancements",
    tags: ["race-condition", "backend", "otp"],
    updated: "2025-11-30T08:12:00Z",
    created: "2025-11-24T10:15:00Z"
  },
  {
    id: "OPS-44",
    title: "Investigate high CPU usage in ECS service",
    type: "Spike",
    status: "IN_PROGRESS",
    priority: "CRITICAL",
    reporter: "DevOps",
    assignee: "Raj",
    sprint: "Sprint 14",
    epic: "Platform Stability",
    tags: ["aws", "ecs", "terraform"],
    updated: "2025-11-30T02:27:00Z",
    created: "2025-11-25T18:03:00Z"
  },
  {
    id: "OPS-45",
    title: "Add retry logic in Kafka producer",
    type: "Task",
    status: "TODO",
    priority: "HIGH",
    reporter: "Amit",
    assignee: "Sagar",
    sprint: "Sprint 15",
    epic: "Message Queue Reliability",
    tags: ["kafka", "backend", "retries"],
    updated: "2025-11-30T09:20:00Z",
    created: "2025-11-29T11:41:00Z"
  },
  {
    id: "PROD-21",
    title: "Optimize bundle size using code splitting",
    type: "Story",
    status: "DONE",
    priority: "MEDIUM",
    reporter: "Aakash",
    assignee: "Aakash",
    sprint: "Sprint 13",
    epic: "Performance Optimizations",
    tags: ["webpack", "react", "performance"],
    updated: "2025-11-19T09:30:00Z",
    created: "2025-11-10T11:33:00Z"
  },
  {
    id: "FRONT-554",
    title: "Fix dark mode color inconsistencies",
    type: "Bug",
    status: "IN_PROGRESS",
    priority: "LOW",
    reporter: "Sara",
    assignee: "Sara",
    sprint: "Sprint 14",
    epic: "UI Enhancements",
    tags: ["dark-mode", "css"],
    updated: "2025-11-29T21:56:00Z",
    created: "2025-11-26T19:03:00Z"
  },
  {
    id: "DASH-94",
    title: "Integrate bar chart for revenue analytics",
    type: "Task",
    status: "TODO",
    priority: "HIGH",
    reporter: "Riya",
    assignee: "Sachin",
    sprint: "Sprint 15",
    epic: "Analytics Dashboard",
    tags: ["charts", "frontend", "recharts"],
    updated: "2025-11-30T05:41:00Z",
    created: "2025-11-27T12:21:00Z"
  },
  {
    id: "AUTH-142",
    title: "Implement secure password policy validation",
    type: "Story",
    status: "TODO",
    priority: "MEDIUM",
    reporter: "Amit",
    assignee: "Anup",
    sprint: "Backlog",
    epic: "Security Enhancements",
    tags: ["auth", "policy", "backend"],
    updated: "2025-11-29T15:20:00Z",
    created: "2025-11-19T17:40:00Z"
  },
  {
    id: "OPS-46",
    title: "Add alerting for database slow queries",
    type: "Task",
    status: "DONE",
    priority: "HIGH",
    reporter: "DevOps",
    assignee: "Raj",
    sprint: "Sprint 12",
    epic: "Platform Stability",
    tags: ["monitoring", "grafana", "database"],
    updated: "2025-11-15T14:11:00Z",
    created: "2025-11-08T09:55:00Z"
  }
];
